<?php

require_once 'wp-content/themes/skdesign/framework/module/testtaxonomy/AbstractClassTest.php';

use sk\module\testtaxonomy\AbstractClassTest;

class TestZapis extends AbstractClassTest
{
    public function __construct($base, $post_type)
    {
        parent::__construct('tkan', 'product');
    }

    public function get_base()
    {
        return parent::get_base(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}