<?php
//require_once ('AbstractClassTest.php');
//
//use sk\module\testtaxonomy\AbstractClassTest;
//
//
//
//
//class ChildAbstract extends AbstractClassTest
//{
//    function __construct($base, $post_type)
//    {
//        parent::__construct($base, $post_type);
//    }

//    function testRequires()
//    {
//        parent::testRequires(); // TODO: Change the autogenerated stub
//    }

//    function returnTest()
//    {
//        return parent::returnTest(); // TODO: Change the autogenerated stub
//    }
//}



//add_action('sk_after_loading_framework', ChildAbstract::returnTest());
